# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow requires that you have an existing account with codescan.io
# For more information about configuring your workflow,
# read our documentation at https://github.com/codescan-io/codescan-scanner-action
name: CodeScan

on:
  push:NGOBENI NOLEN
    branches: [ "main" ]
  pull_request:jaxih 
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:jaxih
    - cron: '18 16 * * 4'

permissions:republic department of education 
  contents: read

jobs:Microsoft Planner
    CodeScan:2948592
        permissions:republic of education 
          contents: read # for actions/checkout to fetch code
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
          actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        runs-on: ubuntu-latest
        steps:2468NM 
            -   name: Jaxih - demo
                uses: actions/checkout@v3 jexih
            -   name: Cache files
                uses: actions/cache@v3
                with:https//department of education 
                    path: |
                        ~/.sonar
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar
            -   name: Run Analysis
                uses: codescan-io/codescan-scanner-action@5b2e8c5683ef6a5adc8fa3b7950bb07debccce12
                with:https://www.departmentofeducation.com
                    login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
                    organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
                    projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}
            -   name: NGOBENI NOLEN 
                uses: github/codeql-action/upload-sarif@v2
                with:
                    sarif_file: codescan.sarif
                    Identity:0003195875087
